export const entities = {
    // CRUD operations
    sols_sums_crud: "/sols_sums_crud",
    sols_sums_crud_show: "/sols_sums_crud/show",
    sols_sums_crud_anular: "/sols_sums_crud/boton_anular",
    sols_sums_crud_generar: "/sols_sums_crud/boton_generar",
    tipo_reng_sum_crud: '/tipos_rngs_crud',
    delete_tipos_docs: '/tipos_docs_crud',
    pasos_rutas: '/pasos_rutas_crud',
    ccostos_crud: '/ccostos_nivs_crud/',
  
    // Lists
    log_coddependencia: "/sols_sums_crud/lst_coddependencia",
    ccosto: "/sols_sums_crud/lst_ccosto",
    ccostoNiv: '/ccostos_nivs_crud/lst_ccostoniv',
    codaccint: "/sols_sums_crud/lst_codaccint",
    codundcmp: "/sols_sums_crud/lst_codundcmp",
    iddocres: "/sols_sums_crud/lst_iddocres",
    nombnorm: "/sols_sums_crud/lst_nombnorm",
    tiporengsum: "/sols_sums_crud/lst_tiporengsum",
    itemcat: "/sols_sums_crud/lst_itemcat",
    unidmedida: "/sols_sums_crud/lst_unidmedida",
    porcimptos: "/sols_sums_crud/lst_porcimptos",
    servicioscat: "/sols_sums_crud/lst_servicioscat",
    codclasifsnc: "/sols_sums_crud/lst_codclasifsnc",
    ctaspresup: "/sols_sums_crud/lst_ctaspresup",
    ctas: "/sols_sums_crud/lst_ctas",
    lst_comprdores_cot: "listas/lst_compradores",
    provedores: "/listas/lst_proveedores",
    undcompra_comprador: "/listas/unidcompra_comprador",
    lst_catgimp: "/listas/lst_catgimp",
    lst_sistemas: "listas/lst_sistemas",
    lst_servicioscat: "/listas/lst_servicioscat",
    lst_ctaspresup: "/listas/lst_ctaspresup",
    lst_undscompras: "/listas/lst_undscompras",
    lst_ccosto: "/listas/lst_ccosto",
    lst_codgrupo: "/listas/lst_codgrupo",
    lst_tipocompra: "listas/lst_tipodoccom",
    lst_reportes: "/listas/lst_kntreportes_comp",
    lst_contador: '/listas/lst_tipocontador',
    lst_superusuarios: 'listas/lst_superusuarios',
    lst_ujecutora: 'listas/lst_ujec',
    
  
    // Other entities
    documentos: "/documentos_origen",
    eventos_admon: "/eventos_admon",
    compra: "/sol_compras",
    anularCotizacion: "/sol_compras/boton_anular_sc",
    anularRenglon: "/sol_compras/boton_anular_rngsc",
    comprador: "/listas/lst_compradores",
    asig_comprador: "/sol_compras/boton_asig_comprador",
    cotizaciones: "cotizaciones",
    boton_reasig_comp: "cotizaciones/boton_reasig_comprador",
    gen_cotizaciones: "/sol_compras/boton_generar_cotizaciones",
    rengs_sums: "/rengs_sums/show",
    sit_reng_sol_compra_alm: "rengs_sols_compras/sit_reng_sol_compra_alm",
    coletilla: "/coletillas",
    dets_reng_cotiz_show: "/dets_reng_cotiz/show_rng",
    dets_reng_cotiz: "/dets_reng_cotiz",
    reng_cotizacion: "/reng_cotizaciones",
    boton_rechazar_cot: "cotizaciones/boton_rechazar_cot",
    sols_sums_mods: "/sols_sums_mods",
    tipo_reng_sum: '/tipos_rngs_sums',
    docs_logs: 'docs_logs',
    tcambioss: "/cambios_ss",
    ttdocsum: "/tipos_docs",
    ctrls_logs: "/ctrls_logs",
    beneficiarios: "/beneficiarios",
    rutas: "/rutas",
    tipo_docs: "/tipos_docs",
    contactos: "/contactos",
    unidades_compras: "/unidades_compras",
    ruteo_undscompras: "/ruteo_undscompras",
    criterios: "/criterios_eval",
    tiposcomp_unidades: "/tiposcomp_unidades",
    compradores: "/compradores",
    nivs_auts: '/nivs_auts',
    proveedores: '/proveedores',
    tipos_doc_com: '/tipos_doc_com',
    tipos_doc: '/tipos_doc',
    sols_sums: '/sols_sums/?',
  };
  
